language: cpp
compiler:
  - gcc
addons:
  apt:
    packages:
      - lcov
      - gcc-avr
      - binutils-avr
      - avr-libc
script: 
  - ./build-avr.sh
  - ./build.sh
  - make test -C build
after_success:
  - bash <(curl -s https://codecov.io/bash) -f build/total.info || echo "Codecov did not collect coverage reports"