language: cpp
compiler:
  - gcc
addons:
  apt:
    packages: lcov
script: ./travis.sh
after_success:
  - bash <(curl -s https://codecov.io/bash) -f build/total.info || echo "Codecov did not collect coverage reports"